### ISSUE TITLE
Unicode normalisation

### ISSUE THREAD

**Issue by aryamanarora** [UniversalDependencies/UD_Punjabi-PunTB#6]
Hello @dan-zeman, was just looking at the [validation report](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Punjabi-PunTB) for the treebank and noticed many errors regarding unicode normalisation. It seems that Unicode should be decomposed (so GURMUKHI LETTER ZA > GURMUKHI LETTER JA + NUKTA), so I ran the text of the treebank through Python's `unicodedata` NFD decomposition, which should have separated all the diacritics. But it's still giving validation errors about Unicode, and I'm not sure why.

**Comment by dan-zeman** [comment]
The [NFC normalization](https://github.com/UniversalDependencies/tools/blob/b0967d44a14aee4c7e8dc998aa1afa884d30eb96/validate.py#L214) is not just decomposition, it is decomposition followed by canonical composition. You can either use the Python command from the validator (linked above), or you can run your data through the Perl script [normalize_unicode.pl](https://github.com/UniversalDependencies/tools/blob/master/normalize_unicode.pl), also available in the tools repository.

Unfortunately, the validation error messages are sometimes misleading because they report the first unexpected Unicode character but you often also want to see the next character.
